name: SQLProjectImports
description: ''
version: 0.0.1
author: sumitpaul@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/testq1:
    name: testq1
    description: ''
    fabricUID: 32015
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2026-04-07 07:49:01'
    author: sumitpaul@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2026-02-04 10:20:16'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/aa:
    name: aa
    schema: null
    description: null
    author: sumitpaul@prophecy.io
    files:
    - models/aa.sql
    - .prophecy/ide/models/aa.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2026-04-01 10:13:46'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: sumitpaul@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2026-02-04 10:20:30'
  .prophecy/metadata/sqlmacros/prophecy_tmp_source:
    name: prophecy_tmp_source
    macroType: expression
    description: null
    author: sumitpaul@prophecy.io
    files:
    - macros/prophecy_tmp_source.sql
    - .prophecy/ide/macros/prophecy_tmp_source.json
    createdAt: '2026-02-04 10:21:11'
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/var_hello__aa:
    name: var_hello__aa
    description: null
    author: sumitpaul@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2026-04-02 05:16:50'
    tables:
    - name: aa
      schema:
        entityType: ''
        providerType: bigquery
        fields: []
      description: null
      author: sumitpaul@prophecy.io
      createdAt: '2026-04-02 05:16:50'
      tableType: table
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: sumitpaul@prophecy.io
  createdAt: '2026-02-04 10:20:16'
dependencies: []
projectDependencies:
  '78064':
    projectUID: 78064
    projectName: prophecy_basics
    repositoryPath: gitUri=https://github.com/prophecy-io/prophecy-basics&subPath=
    version: 1.0.6
    isDefault: true
    author: null
    createdAt: '2026-02-04 10:19:57'
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
projectConfigurations: {}
sqlOrchestratorPipelines:
  .prophecy/metadata/sqlorchestratorpipeline/test_imports:
    name: test_imports
    schema: null
    description: null
    author: sumitpaul@prophecy.io
    files:
    - .prophecy/ide/pipelines/test_imports.json
    - pipelines/test_imports.py
    - models/test_imports/test_imports__order_status_tracking.sql
    - models/test_imports/schema.yml
    createdAt: '2026-02-04 10:21:11'
sqlBusinessApps: {}
